const languageMap = new Map([
  ["af", "Afrikaans"],
  ["sq", "Albanian"],
  ["am", "Amharic"],
  ["ar", "Arabic"],
  ["hy", "Armenian"],
  ["as", "Assamese"],
  ["az", "Azerbaijani"],
  ["eu", "Basque"],
  ["be", "Belarusian"],
  ["bn", "Bengali"],
  ["bs", "Bosnian"],
  ["bg", "Bulgarian"],
  ["my", "Burmese"],
  ["ca", "Catalan"],
  ["ckb", "Central Kurdish"],
  ["zh", "Chinese"],
  ["hr", "Croatian"],
  ["cs", "Czech"],
  ["da", "Danish"],
  ["nl", "Dutch"],
  ["en", "English"],
  ["et", "Estonian"],
  ["pi", "Filipino"],
  ["fi", "Finnish"],
  ["fr", "French"],
  ["ka", "Georgian"],
  ["de", "German"],
  ["el", "Greek"],
  ["gu", "Gujarati"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["hu", "Hungarian"],
  ["is", "Icelandic"],
  ["id", "Indonesian"],
  ["it", "Italian"],
  ["jp", "Japanese"],
  ["kn", "Kannada"],
  ["kh", "Khmer"],
  ["rw", "Kinyarwanda"],
  ["ko", "Korean"],
  ["lv", "Latvian"],
  ["lt", "Lithuanian"],
  ["lb", "Luxembourgish"],
  ["mk", "Macedonian"],
  ["ms", "Malay"],
  ["ml", "Malayalam"],
  ["mt", "Maltese"],
  ["mi", "Maori"],
  ["mr", "Marathi"],
  ["mn", "Mongolian"],
  ["ne", "Nepali"],
  ["no", "Norwegian"],
  ["or", "Oriya"],
  ["ps", "Pashto"],
  ["fa", "Persian"],
  ["pl", "Polish"],
  ["pt", "Portuguese"],
  ["pa", "Punjabi"],
  ["ro", "Romanian"],
  ["ru", "Russian"],
  ["sm", "Samoan"],
  ["sr", "Serbian"],
  ["sn", "Shona"],
  ["si", "Sinhala"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["so", "Somali"],
  ["es", "Spanish"],
  ["sw", "Swahili"],
  ["sv", "Swedish"],
  ["tg", "Tajik"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["th", "Thai"],
  ["tr", "Turkish"],
  ["tk", "Turkmen"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["uz", "Uzbek"],
  ["vi", "Vietnamese"],
  ["cy", "Welsh"],
]);

const countryMap = new Map([
  ["af", "Afghanistan"],
  ["al", "Albania"],
  ["dz", "Algeria"],
  ["ao", "Angola"],
  ["ar", "Argentina"],
  ["au", "Australia"],
  ["at", "Austria"],
  ["az", "Azerbaijan"],
  ["bh", "Bahrain"],
  ["bd", "Bangladesh"],
  ["bb", "Barbados"],
  ["by", "Belarus"],
  ["be", "Belgium"],
  ["bm", "Bermuda"],
  ["bt", "Bhutan"],
  ["bo", "Bolivia"],
  ["ba", "Bosnia And Herzegovina"],
  ["br", "Brazil"],
  ["bn", "Brunei"],
  ["bg", "Bulgaria"],
  ["bf", "Burkina Faso"],
  ["kh", "Cambodia"],
  ["cm", "Cameroon"],
  ["ca", "Canada"],
  ["cv", "Cape Verde"],
  ["ky", "Cayman Islands"],
  ["cl", "Chile"],
  ["cn", "China"],
  ["co", "Colombia"],
  ["km", "Comoros"],
  ["cr", "Costa Rica"],
  ["ci", "Côte d'Ivoire"],
  ["hr", "Croatia"],
  ["cu", "Cuba"],
  ["cy", "Cyprus"],
  ["cz", "Czech Republic"],
  ["dk", "Denmark"],
  ["dj", "Djibouti"],
  ["dm", "Dominica"],
  ["do", "Dominican Republic"],
  ["cd", "DR Congo"],
  ["ec", "Ecuador"],
  ["eg", "Egypt"],
  ["sv", "El Salvador"],
  ["ee", "Estonia"],
  ["et", "Ethiopia"],
  ["fj", "Fiji"],
  ["fi", "Finland"],
  ["fr", "France"],
  ["pf", "French Polynesia"],
  ["ga", "Gabon"],
  ["ge", "Georgia"],
  ["de", "Germany"],
  ["gh", "Ghana"],
  ["gr", "Greece"],
  ["gt", "Guatemala"],
  ["gn", "Guinea"],
  ["ht", "Haiti"],
  ["hn", "Honduras"],
  ["hk", "Hong Kong"],
  ["hu", "Hungary"],
  ["is", "Iceland"],
  ["in", "India"],
  ["id", "Indonesia"],
  ["iq", "Iraq"],
  ["ie", "Ireland"],
  ["il", "Israel"],
  ["it", "Italy"],
  ["jm", "Jamaica"],
  ["jp", "Japan"],
  ["jo", "Jordan"],
  ["kz", "Kazakhstan"],
  ["ke", "Kenya"],
  ["kw", "Kuwait"],
  ["kg", "Kyrgyzstan"],
  ["lv", "Latvia"],
  ["lb", "Lebanon"],
  ["ly", "Libya"],
  ["lt", "Lithuania"],
  ["lu", "Luxembourg"],
  ["mo", "Macau"],
  ["mk", "Macedonia"],
  ["mg", "Madagascar"],
  ["mw", "Malawi"],
  ["my", "Malaysia"],
  ["mv", "Maldives"],
  ["ml", "Mali"],
  ["mt", "Malta"],
  ["mr", "Mauritania"],
  ["mx", "Mexico"],
  ["md", "Moldova"],
  ["mn", "Mongolia"],
  ["me", "Montenegro"],
  ["ma", "Morocco"],
  ["mz", "Mozambique"],
  ["mm", "Myanmar"],
  ["na", "Namibia"],
  ["np", "Nepal"],
  ["nl", "Netherlands"],
  ["nz", "New Zealand"],
  ["ne", "Niger"],
  ["ng", "Nigeria"],
  ["kp", "North Korea"],
  ["no", "Norway"],
  ["om", "Oman"],
  ["pk", "Pakistan"],
  ["pa", "Panama"],
  ["py", "Paraguay"],
  ["pe", "Peru"],
  ["ph", "Philippines"],
  ["pl", "Poland"],
  ["pt", "Portugal"],
  ["pr", "Puerto Rico"],
  ["ro", "Romania"],
  ["ru", "Russia"],
  ["rw", "Rwanda"],
  ["ws", "Samoa"],
  ["sm", "San Marino"],
  ["sa", "Saudi Arabia"],
  ["sn", "Senegal"],
  ["rs", "Serbia"],
  ["sg", "Singapore"],
  ["sk", "Slovakia"],
  ["si", "Slovenia"],
  ["sb", "Solomon Islands"],
  ["so", "Somalia"],
  ["za", "South Africa"],
  ["kr", "South Korea"],
  ["es", "Spain"],
  ["lk", "Sri Lanka"],
  ["sd", "Sudan"],
  ["se", "Sweden"],
  ["ch", "Switzerland"],
  ["sy", "Syria"],
  ["tw", "Taiwan"],
  ["tj", "Tajikistan"],
  ["tz", "Tanzania"],
  ["th", "Thailand"],
  ["to", "Tonga"],
  ["tn", "Tunisia"],
  ["tr", "Turkey"],
  ["tm", "Turkmenistan"],
  ["ug", "Uganda"],
  ["ua", "Ukraine"],
  ["ae", "United Arab Emirates"],
  ["gb", "United Kingdom"],
  ["us", "United States of America"],
  ["uy", "Uruguay"],
  ["uz", "Uzbekistan"],
  ["ve", "Venezuela"],
  ["vi", "Vietnam"],
  ["ye", "Yemen"],
  ["zm", "Zambia"],
  ["zw", "Zimbabwe"],
]);

function getCodesByNames(names, map) {
  const codes = names.map((name) => {
    for (const [code, fullName] of map.entries()) {
      if (fullName === name) {
        return code;
      }
    }
    return null; // Return null for unknown names
  });
  return codes;
}
export function categoryMapper(
  selectedCategories,
  selectedLanguages,
  selectedCountries
) {
  const categoriesLowercase = selectedCategories.map((element) =>
    element.toLowerCase()
  );
  const languageCodes = getCodesByNames(selectedLanguages, languageMap);
  const countryCodes = getCodesByNames(selectedCountries, countryMap);

  return {
    categoriesLowercase,
    languageCodes,
    countryCodes,
  };
}
